apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-secrets-external
  namespace: microservices
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-banking-store
    kind: SecretStore
  target:
    name: app-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    # MySQL
    - secretKey: mysql-password
      remoteRef:
        key: mysql
        property: password
    
    # Gmail
    - secretKey: mail-host
      remoteRef:
        key: gmail
        property: host
    - secretKey: mail-port
      remoteRef:
        key: gmail
        property: port
    - secretKey: mail-username
      remoteRef:
        key: gmail
        property: username
    - secretKey: mail-password
      remoteRef:
        key: gmail
        property: password
    
    # Cloudinary
    - secretKey: cloudinary-cloud-name
      remoteRef:
        key: cloudinary
        property: cloud-name
    - secretKey: cloudinary-api-key
      remoteRef:
        key: cloudinary
        property: api-key
    - secretKey: cloudinary-api-secret
      remoteRef:
        key: cloudinary
        property: api-secret
    
    # JWT (bonus)
    - secretKey: jwt-secret
      remoteRef:
        key: jwt
        property: secret

    - secretKey: aes-key
      remoteRef:
        key: aes
        property: key