apiVersion: external-secrets.io/v1   # ← change v1beta1 en v1
kind: SecretStore
metadata:
  name: vault-banking-store
  namespace: microservices
spec:
  provider:
    vault:
      server: "http://vault.vault-system.svc.cluster.local:8200"
      path: "banking"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "eso-role"
          serviceAccountRef:
            name: eso-vault-sa