apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: microservices
type: Opaque
stringData:
  # MySQL
  mysql-password: root

  # Gmail SMTP
  mail-host: smtp.gmail.com
  mail-port: "587"
  mail-username: basma53125@gmail.com
  mail-password: "kzii eduh kkdk rxem"

  # Cloudinary
  cloudinary-cloud-name: dbosjotn0
  cloudinary-api-key: "253268393373744"
  cloudinary-api-secret: 6HIs9nNbgSFIPZbb3VXYQL7n9rg