server:
  dev:
    enabled: true
    devRootToken: "root-token-banking-2026"
  
  ha:
    enabled: false
  
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m
  
  service:
    type: ClusterIP

ui:
  enabled: true
  serviceType: "ClusterIP"

injector:
  enabled: false