apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-registry
  template:
    metadata:
      labels:
        app: service-registry
    spec:
      containers:
        - name: service-registry
          image: springboot-kafka-microservices/eureka-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: EUREKA_INSTANCE_HOSTNAME
              value: eureka-server
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "false"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "300m"
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: microservices
spec:
  selector:
    app: service-registry
  ports:
    - port: 8761
      targetPort: 8761
      nodePort: 30761
  type: NodePort